name: TaskFlow CI

# O workflow será disparado sempre que houver um push ou pull request na branch main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o download do código do teu repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente com o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-node: 20
          cache: 'npm' # Faz cache das dependências para o processo ser mais rápido nas próximas vezes

      # 3. Instala as dependências do projeto (incluindo lucide-react, sonner, etc.)
      - name: Install dependencies
        run: npm ci

      # 4. Executa o build do Vite + TypeScript para garantir que não há erros de compilação
      - name: Build project
        run: npm run build